commit (HW7)
Awalone01/2.0HW5 pull request #2
Opened 2022-02-13 16:29 UTC by Awalone01

2022-02-13 17:51 UTC, rmuhamedgaliev requested changes
Требуются правки 🎯

2022-02-13 17:51 UTC, rmuhamedgaliev commented on src/main/java/pro/sky2/HW5/service/EmployeeMapService.java
>  public interface EmployeeMapService {
Тебе надо сделать так 
- удалить EmployeeMapService и EmployeeMapServiceImpl 
- Переписать EmployeeService - что бы он например просто возвращал в методе getAllEmployees например List<Employee>, что бы не быть зависимым от внутренних типов
- изменить реализацию EmployeeServiceImpl, что бы она использовала Map как тип храненния данных согласно заданию - https://skyengpublic.notion.site/2-7-Generics-Map-8f9c9a87368d4ed9811f43e419bdb054

2022-02-13 17:51 UTC, rmuhamedgaliev commented on src/main/java/pro/sky2/HW5/controller/EmployeeController.java
>                                   @RequestParam("lastName") String lastName) {
Если ты везде аннтоции стараешься выравнивать в методах, то выравнивай везде, а то сейчас выглядит так что выравнивание "плаяшет"

2022-02-13 17:51 UTC, rmuhamedgaliev commented on src/main/java/pro/sky2/HW5/service/impl/EmployeeMapServiceImpl.java
В методе 

```
    @Override
    public Map<String, Employee> getAllEmployees() {
        for (Map.Entry<String, Employee> pair : employees.entrySet()) {
            String key = pair.getKey();
            Employee value = pair.getValue();
            System.out.println(key + ":" + value);
        }
        return employees;
    }
```

Вывод в консоль вообще не нужен,

2022-02-13 17:51 UTC, rmuhamedgaliev commented on src/main/java/pro/sky2/HW5/service/impl/EmployeeMapServiceImpl.java
А для того что бы возвращать из интерфейса List просто так можешь сделать 

> return new ArrayList<>(employees.values());

2022-02-16 18:14 UTC, rmuhamedgaliev approved these changes
Удали закомментированный код, а в остальном все хорошо.

2022-02-16 18:14 UTC, rmuhamedgaliev commented on src/main/java/pro/sky2/HW5/service/impl/EmployeeServiceImpl.java
> +//        String key = firstName + lastName;
Закомментированный код можешь смело удалять. Комментарии нужны если ты описываешь логику, но закомментированный код не нужно хранить

2022-02-16 18:17 UTC, Awalone01 commented on src/main/java/pro/sky2/HW5/service/impl/EmployeeServiceImpl.java
> +//        String key = firstName + lastName;
> Закомментированный код можешь смело удалять. Комментарии нужны если ты описываешь логику, но закомментированный код не нужно хранить

Да, хорошо! Спасибо за твои наставления и обьяснения про GitFlow)))

2022-02-16 18:22 UTC, merged